// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview An AI agent for validating video content to ensure originality and relevance to sustainability themes.
 *
 * - validateVideoContent - A function that handles the video content validation process.
 * - ValidateVideoContentInput - The input type for the validateVideoContent function.
 * - ValidateVideoContentOutput - The return type for the validateVideoContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ValidateVideoContentInputSchema = z.object({
  videoDescription: z.string().describe('The description of the video content.'),
  videoUrl: z.string().describe('URL of the video content to analyze.'),
});
export type ValidateVideoContentInput = z.infer<typeof ValidateVideoContentInputSchema>;

const ValidateVideoContentOutputSchema = z.object({
  isOriginal: z.boolean().describe('Whether the video content is original.'),
  isRelevant: z.boolean().describe('Whether the video content is relevant to sustainability themes.'),
  reasoning: z.string().describe('The reasoning behind the originality and relevance assessment.'),
});
export type ValidateVideoContentOutput = z.infer<typeof ValidateVideoContentOutputSchema>;

export async function validateVideoContent(input: ValidateVideoContentInput): Promise<ValidateVideoContentOutput> {
  return validateVideoContentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'validateVideoContentPrompt',
  input: {schema: ValidateVideoContentInputSchema},
  output: {schema: ValidateVideoContentOutputSchema},
  prompt: `You are an AI video content validator for a sustainability platform.

You will analyze the video content based on the description provided and determine if it is original and relevant to sustainability themes.

Description: {{{videoDescription}}}
Video URL: {{{videoUrl}}}

Determine the following:
- isOriginal: Is the video content original?
- isRelevant: Is the video content relevant to sustainability themes?
- reasoning: Provide the reasoning behind the originality and relevance assessment.

Return the output in JSON format.`,
});

const validateVideoContentFlow = ai.defineFlow(
  {
    name: 'validateVideoContentFlow',
    inputSchema: ValidateVideoContentInputSchema,
    outputSchema: ValidateVideoContentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
